version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Docker2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  api:
    build: .
    ports: 
      - "8090:80"